### ISSUE TITLE
URL from README is not avaible

### ISSUE THREAD

**Issue by Roker2** [buckket/kindle-abfahrt#2]
I tried to open this URL and GitHub gave 404 error
github.com/gobuffalo/packr/v2/packr2

**Comment by Roker2** [comment]
Did you mean it maybe?
https://github.com/gobuffalo/packr/tree/master/v2/packr2

**Comment by buckket** [comment]
The URL is formatted so that ```go get``` fetches the correct version of packr.
It’s not a direct link to the git repo.

**Comment by Roker2** [comment]
Oh, okay, sorry. It is one more knowledge, thanks.
